# Generated by Django 4.2.4 on 2023-09-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadith',
            name='category',
            field=models.CharField(blank=True, choices=[('Hadith', 'Hadith'), ('Quran', 'Quran'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
